import Head from "next/head";
import Navbar from "../../components/Navbar";
import SocialButton from "../../components/SocialButton";
import Dribble from '../../public/dribbble.svg'
import Instagram from '../../public/instagram.svg'
import Twitter from '../../public/twitter.svg'
import Linkedin from  '../../public/linkedin.svg'
import ProjectPreview from "../../components/ProjectPreview";
import Github from "../../public/github.svg"

export default function Home() {
  return (
    <>
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      
      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4">

        <div className="h=[30rem] rounded-3xl p-10 flex flex-col gap-16 bg-[url('/gradient-bg.jpg')] bg-cover">
          <h1 className="text-4xl font-semibold">Hello I'm Rayaan, a Software Engineer with 5 years of experience.</h1>
          <p className="flex-1">I care a lot about using software engeering for a positive impact and enjoy
            creating user-centric, delightful, and human experiences
          </p>

          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <button className="bg-black text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto">Contact me</button>
            <div className="flex items-center gap-4">
              
              <SocialButton bgColor="github">
                <Github className="w-6 h-6"/>
              </SocialButton>

              <SocialButton bgColor="linkedin">
                <Linkedin className="w-5 h-5"/>
              </SocialButton>
            </div>
          </div>
        </div>
        <div className="h-[30rem] rounded-3xl p-8 bg-[url('/profile.jpg')] bg-cover bg-center"/>
      </section>  

      <section className="grid grid-cols-1 lg:grid-cols-2 gap-4 my-4">
        <ProjectPreview
          name="Huberman AI"
          description="Get scientifically accurate answers"
          imageUrl="/project-1.png"
          bgColor="#C5DAD2"
          // dark
          link="https://research2-slides-front-end.vercel.app/"
        />
        <ProjectPreview
          name="Airport Management System"
          description="Manage all aspects of an airport"
          imageUrl="/project-2.png"
          bgColor="#414422"
          dark
          link="https://github.com/Rayaan-khan428/Airline-Management-System"
          
        />
        <ProjectPreview
          name="Research2Slides"
          description="Convert research papers to powerpoints!"
          imageUrl="/project-3.png"
          // bgColor="#4e4e56"
          // dark
          link="https://research2-slides-front-end.vercel.app/"
        />
        <ProjectPreview
          name="Huberman AI"
          description="Get scientifically accurate answers to your questions"
          imageUrl="/project-3.png"
          bgColor="linear-gradient(138deg, rgba(228,228,231,1) 12%, rgba(245,227,189,1) 84%);"
        />
      </section>

      {/* footer section */}
      <section className="grid grid-cols-1 mb-8">
        <div className="h=[30rem] rounded-3xl p-10 flex flex-col gap-16 bg-[url('/gradient-bg.jpg')] bg-cover">
          <h1 className="text-4xl font-semibold">Want to work together?</h1>
          <p className="flex-1">Feel free to reach out to collaborate on something or just say hello! <br></br> rayaan.k.ca@gmail.com
          </p>

          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <button className="bg-black text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto">Contact me</button>
            <div className="flex items-center gap-4">
              
              <SocialButton bgColor="github">
                <Github className="w-6 h-6"/>
              </SocialButton>


              <SocialButton bgColor="linkedin">
                <Linkedin className="w-5 h-5"/>
              </SocialButton>
            </div>
          </div>
        </div>
      </section>  


    </>
  );
}
